package com.carlesramos.model;
// Generated 12 feb. 2020 13:14:37 by Hibernate Tools 5.2.12.Final

/**
 * Cartas generated by hbm2java
 */
public class Cartas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idcarta;
	private String marca;
	private String modelo;
	private String pais;
	private long motor;
	private int potenciaKw;
	private int potenciaCv;
	private int numCilindros;
	private int velocidad;
	private int revoluciones;
	private long consumo;
	private RankingCartas rankingCartas;

	public Cartas() {
	}

	public Cartas(String marca, String modelo, String pais, long motor, int potenciaKw, int potenciaCv,
			int numCilindros, int velocidad, int revoluciones, long consumo) {
		this.marca = marca;
		this.modelo = modelo;
		this.pais = pais;
		this.motor = motor;
		this.potenciaKw = potenciaKw;
		this.potenciaCv = potenciaCv;
		this.numCilindros = numCilindros;
		this.velocidad = velocidad;
		this.revoluciones = revoluciones;
		this.consumo = consumo;
	}

	public Cartas(String marca, String modelo, String pais, long motor, int potenciaKw, int potenciaCv,
			int numCilindros, int velocidad, int revoluciones, long consumo, RankingCartas rankingCartas) {
		this.marca = marca;
		this.modelo = modelo;
		this.pais = pais;
		this.motor = motor;
		this.potenciaKw = potenciaKw;
		this.potenciaCv = potenciaCv;
		this.numCilindros = numCilindros;
		this.velocidad = velocidad;
		this.revoluciones = revoluciones;
		this.consumo = consumo;
		this.rankingCartas = rankingCartas;
	}

	public Integer getIdcarta() {
		return this.idcarta;
	}

	public void setIdcarta(Integer idcarta) {
		this.idcarta = idcarta;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public long getMotor() {
		return this.motor;
	}

	public void setMotor(long motor) {
		this.motor = motor;
	}

	public int getPotenciaKw() {
		return this.potenciaKw;
	}

	public void setPotenciaKw(int potenciaKw) {
		this.potenciaKw = potenciaKw;
	}

	public int getPotenciaCv() {
		return this.potenciaCv;
	}

	public void setPotenciaCv(int potenciaCv) {
		this.potenciaCv = potenciaCv;
	}

	public int getNumCilindros() {
		return this.numCilindros;
	}

	public void setNumCilindros(int numCilindros) {
		this.numCilindros = numCilindros;
	}

	public int getVelocidad() {
		return this.velocidad;
	}

	public void setVelocidad(int velocidad) {
		this.velocidad = velocidad;
	}

	public int getRevoluciones() {
		return this.revoluciones;
	}

	public void setRevoluciones(int revoluciones) {
		this.revoluciones = revoluciones;
	}

	public long getConsumo() {
		return this.consumo;
	}

	public void setConsumo(long consumo) {
		this.consumo = consumo;
	}

	public RankingCartas getRankingCartas() {
		return this.rankingCartas;
	}

	public void setRankingCartas(RankingCartas rankingCartas) {
		this.rankingCartas = rankingCartas;
	}

}
